language: python
sudo: false
cache:
  directories:
  - $HOME/.pip-cache/
python:
- '2.7'
env:
  matrix:
  - DJANGO=django==1.9.6"
install:
- pip install -e .[test] --process-dependency-links --trusted-host github.com
script:
- python ./setup.py test
